# Generated by Django 4.2 on 2025-02-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='github_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link do GitHub'),
        ),
        migrations.AddField(
            model_name='person',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Instagram'),
        ),
        migrations.AddField(
            model_name='person',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link do LinkedIn'),
        ),
    ]
